"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var INIT_SCREEN = exports.INIT_SCREEN = "INIT_SCREEN";
var HANDLE_SCREEN_CONFIGURATION_FIELD_CHANGE = exports.HANDLE_SCREEN_CONFIGURATION_FIELD_CHANGE = "HANDLE_SCREEN_CONFIGURATION_FIELD_CHANGE";
var PREPARE_FINAL_OBJECT = exports.PREPARE_FINAL_OBJECT = "PREPARE_FINAL_OBJECT";
var FORM_SUBMIT = exports.FORM_SUBMIT = "FORM_SUBMIT";